### PR TITLE
FEATURE: PCI-4455 Fix unit test suite for custom/folsom

### PR DESCRIPTION
**Pull request by ytsarev**
Ran 3732 tests in 723.907s

OK (SKIP=23)

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/openstack-nova-unittests/38/

**Comment by ytsarev** [comment]
ok to test

**Comment by ytsarev** [comment]
ok to test

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/openstack-nova-folsom-unittests/10/

**Comment by ytsarev** [comment]
Job was reconfigured to manual invocation due to security concerns described in https://jira.intgdc.com/browse/PCI-4454

See
https://ci.intgdc.com/pview/job/openstack-nova-folsom-unittests/18/

This PR can be merged

**Comment by zarnovican-gd** [comment]
I'm still not comfortable with the "except KeyError". I believe the primary problem is that in patch "1005-use-local-LVM-volume-instead-of-iSCSI-device-on-same.patch" there were two topics mixed up together. 1) use direct LVM device 2) use volume by EC2 id if found. There is no reason to preserve that EC2 code. And my guess is that it might be also the reason for KeyErrors.

I believe this is the original patch. 
https://git.intgdc.com/?p=packages/openstack-nova.git;a=blob;f=1005-use-local-LVM-volume-instead-of-iSCSI-device-on-same.patch;h=e7a81477e40473166a4992d4d2b5488e61f63aa6;hb=refs/heads/stable/essex

It could be adapted to use uuid instead of ec2, which will remove the only external call that could cause that KeyError.

Now the question is, whether this approach would be more or _less_ disruptive than ignoring KeyError exceptions ?

**Comment by zarnovican-gd** [comment]
:+1: 

After short discussion with Tomas, I agreed to accept it even with "except KeyError" statement. It is caused by lookup into `connection_info['data']['volume_id']`, which is working in real use cases, but failing in some tests.

**Pull request merged**
