### PR TITLE
CONFIG: PAAS-7486 add dependency to network

### PR DESCRIPTION
**Pull request by msurovcak**

### CODE REVIEW

**Comment by msurovcak** [comment]
@k0da we have agreed that we won't do a new build, it will be responsibility of future builder to add all the changes between last release and build

**Comment by k0da** [comment]
Why? Why? It just a one line addition, and reduced work for next commiter

**Comment by msurovcak** [comment]
@k0da changed

**Comment by k0da** [comment]
Timestamp

**Comment by msurovcak** [comment]
@k0da so it is not one line! :) fixed

**Pull request merged**
